# Generated by Django 4.1.1 on 2022-09-18 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='skills',
            new_name='job_type',
        ),
    ]
